### ISSUE TITLE
Consider dummy repository for testing

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-python#10]
@SuperKogito we are currently using your personal site for most tests, and there are quite a few files! What do you think about creating a dummy (smaller version of it) here, and then using that for consistent testing?

**Comment by SuperKogito** [comment]
this is actually the purpose of https://github.com/urlstechie/URLs-checker-test-repo (we should probably rename it for the sake of consistency) but that should be the dummy for testing. It is more professional than using my website.

**Comment by SuperKogito** [comment]
You can add any files and links in there that you deem useful for the testing

**Comment by vsoch** [comment]
ah okay, let me rename and then do a PR to update the tests. How about urlchecker-test-repo?

**Comment by SuperKogito** [comment]
I just renamed it.  `urlchecker-test-repo` it is :rocket:

**Comment by vsoch** [comment]
This will be closed by #11

**Comment by vsoch** [comment]
This is all set.
