### ISSUE TITLE
create conda package

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-python#18]

**Comment by vsoch** [comment]
See https://github.com/conda-forge/staged-recipes/pull/11138! @SuperKogito when you get back you can confirm being a maintainer there, and then it can be merged and will create us a urlchecker-feedstock repository that will update automatically with releases to pypi.

**Comment by SuperKogito** [comment]
I just approved the changes in https://github.com/conda-forge/staged-recipes/pull/11138, that should do it I hope. If I need to do something else to confirm being a maintainer,  please let me know :)

**Comment by vsoch** [comment]
We’re done!
