### ISSUE TITLE
Refactor check into class, print results with filename

### ISSUE THREAD

**Issue by maelle** [urlstechie/urlchecker-python#24]
last question from me for a while I promise :-)

**Comment by vsoch** [comment]
It doesn’t include that, but you are right it should! I’ll fix this tomorrow. But not in 5 minutes tomorrow, after some sleep :)

**Comment by vsoch** [comment]
@SuperKogito what are your thoughts for how to address this? Since we pass urls around the library (and leave the files behind) it's a nontrivial thing to be able to get them later. My thinking is that when we first parse through the files, we would need to also create some kind of lookup (dictionary) for later use.

**Comment by SuperKogito** [comment]
well there is an easy fix using `check_results = {"passed": [], "failed": []}`. We can use it to get the results of each file checks and use it in:
https://github.com/urlstechie/urlchecker-python/blob/ea1e13e6392d41512747119e42f382b56e6360a7/urlchecker/core/check.py#L97

To update another dict that looks like this  `files_check_results = {"file_1":  {"passed": [], "failed": []}, ..., "file_n" : {"passed": [], "failed": []}}`

**Comment by vsoch** [comment]
And then parse over the doubly nested dictionary to save and print to the terminal? The issue here is that we couldn’t just cleanly check a single key (eg failed) to determine if it passed.

I think the most elegant solution would be to implement an actual class that can hold results and then accurately quickly report if it’s failed or not I’ll make some time for it over this weekend.

**Comment by vsoch** [comment]
heads up @SuperKogito I have a pretty big refactor coming in, it will be a lot of changes so please hold back working on other issues! I'm not sure about ETA but if not today, likely tomorrow.

**Comment by vsoch** [comment]
hey @maelle ! I have PR (currently [WIP](https://github.com/urlstechie/urlchecker-python/pull/31)) where I've added a function to much better handle this, here is a preview of what the saved file looks like:

```
URL,RESULT,FILENAME
https://www.google.com/,passed,/tmp/urlchecker-test-repo.e175dbcs/test_action/sample_test_file.py
https://github.com/urlstechie,passed,/tmp/urlchecker-test-repo.e175dbcs/test_action/sample_test_file.md
https://github.com/urlstechie/urlchecker-python,passed,/tmp/urlchecker-test-repo.e175dbcs/test_action/sample_test_file.md
https://www.google.com/,passed,/tmp/urlchecker-test-repo.e175dbcs/test_action/sample_test_file.md
https://github.com/SuperKogito,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.py
https://www.google.com/,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.py
https://github.com/SuperKogito/URLs-checker/README.md,failed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.py
https://github.com/SuperKogito/spafe/issues/5,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://www.google.com/,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues/1,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues/3,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/Voice-based-gender-recognition,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues/7,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://img.shields.io/,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues/8,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues/2,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/Voice-based-gender-recognition/issues/2,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker/issues,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/Voice-based-gender-recognition/issues/1,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues/4,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/Voice-based-gender-recognition/issues,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/spafe/issues/6,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker/blob/master/README.md,passed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://none.html,failed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker/issues/4,failed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker/issues/1,failed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker/issues/3,failed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker/README.md,failed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
https://github.com/SuperKogito/URLs-checker/issues/2,failed,/tmp/urlchecker-test-repo.e175dbcs/test_files/sample_test_file.md
```
I refactored the checker to be a class (so it's much easier to generate the data structure about, and otherwise interact with a result) so as soon as I can finish up updating tests, we should be able to review and get a testing branch for you on urlchecker-action. Stay tuned!

**Comment by vsoch** [comment]
hey @maelle this is all set! You can see the test that was added to urlchecker-action for the file that is now generated: https://github.com/urlstechie/urlchecker-action/pull/50

And this shows the formatting and that it now includes the filename too.

![image](https://user-images.githubusercontent.com/814322/79078703-5be08b80-7cc7-11ea-9ab9-85864d76c80c.png)

Closing issue as both refactor of check and printing results with filename has been addressed.

**Comment by maelle** [comment]
Thanks, very cool! My plan is to write a workflow uploading the csv as artifact. :-)

**Comment by maelle** [comment]
I'm trying to write a workflow uploading the artifact and have a question. I tried various things and might be missing something obvious regarding paths.

[Workflow](https://github.com/r-hub/docs/blob/gha/.github/workflows/urlchecks.yml)

https://github.com/r-hub/docs/runs/582541285?check_suite_focus=true

* The URL-checks actions is "Saving results to /github/workspace/output/urls.csv"
* But then the upload-artifact function tries to find it in "/home/runner/work/docs/docs/output"

Do you have any tip regarding where it might be best to tweak things?

No worries if you don't answer, I'm not sure this is the right place to ask. :-9

**Comment by SuperKogito** [comment]
This might be what you are looking for, the description fits the use-case but tbh I am not sure how exactly to do the mentioned chmod step. Maybe this can give you a hint, https://github.community/t5/GitHub-Actions/Access-to-path-denied-during-artifact-upload/td-p/33562

**Comment by maelle** [comment]
Thanks! Does the action run in a container? I also saw https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem

**Comment by maelle** [comment]
I suppose my question is, should I tweak my workflow (perfectly fine) or should the action save the CSV in a place that'd be directly accessible by upload-artifact?

**Comment by SuperKogito** [comment]
Technically the action is just a [Docker](https://github.com/urlstechie/urlchecker-action/blob/master/Dockerfile), that uses the python package and we just access it using an [entrypoint](https://github.com/urlstechie/urlchecker-action/blob/master/entrypoint.sh).
Your workflow looks okay to me, but that's a very good question and a fair point, that we should discuss with @vsoch.

**Comment by maelle** [comment]
I'll wait before tweaking any further, then.

My idea was that if the workflow fails, it might be good to look over URLs in some sort of spreadsheets to keep track of fixes/notes, hence my wanting the artifact. And if it doesn't fail the artifact might be fun too (e.g. looking at most frequent domains or so), but less crucial.

**Comment by SuperKogito** [comment]
This was moved to https://github.com/urlstechie/urlchecker-action/issues/51. Let's try to keep topics separate ;)

**Comment by vsoch** [comment]
@maelle I created this simple example to show you saving and then cat of a result file in the next step: https://github.com/urlstechie/urlchecker-action/blob/master/.github/workflows/main.yml#L22. Can you show me your recipe and we can figure out what might be wrong? I don't think that this is a bug in the library, but I'm not totally clear what you are doing. The simple case worked for me.
