### ISSUE TITLE
bug with passing tests despite failed urls

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-python#27]
See https://github.com/r-hub/docs/runs/576617965?check_suite_focus=true

force pass is false, so this should not be successful.

**Comment by vsoch** [comment]
I fixed this locally, will PR soon with the other recent changes that are needed.

**Comment by SuperKogito** [comment]
This is a bug I mentioned in the mess I created last time. The cases of force pass are not handled properly. I think you have enough to do so I can investigate this one ;)

**Comment by vsoch** [comment]
I've already fixed it @SuperKogito

**Comment by vsoch** [comment]
I'm going to triage the --files flag and fixing the bug, then I'll go back to the other issues and discuss what I think you would be great to help with!

**Comment by vsoch** [comment]
This is fixed, thanks @SuperKogito !
