### ISSUE TITLE
Travis runs: enable for only PR?

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-python#3]
As discussed in #2 , Travis currently runs twice (for PR and branch pushes) and it might make sense to only run for PR, since pushing to master won't be a thing (but always done via a pull request). A note from @SuperKogito :
> Well you make a good point about travis running twice. Technically, travis is running once on the new branch and once on the PR. I think we should drop the branch run and settle for one run for the PR? if you think it is slow, we can use pytest-xdist (like I did initially) but the logs won't be as detailed as now :P

**Comment by SuperKogito** [comment]
This seems to be what we are looking for: 
https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda

**Comment by vsoch** [comment]
@SuperKogito if you want to make sure the travis settings has both the build options active (for branch and PR updates) I can try opening a PR to test it out with a changed .travis.yml!

**Comment by SuperKogito** [comment]
A PR sounds like a good idea! I am okay with whatever you choose tho. My main concern is to have travis working cuz I find it helpful ;)

**Comment by vsoch** [comment]
It just worked for #5, so we are good! When that is merged, we can close the issue here. Where is my Staples button?

**Comment by vsoch** [comment]
This is done.
