### ISSUE TITLE
Bug: urls that end with }

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-python#42]
We currently have a bug that urls represented in yaml / json (or another data structure) that end in } are not being correctly parsed. Here is an example:

![image](https://user-images.githubusercontent.com/814322/79903515-7229ce00-83d0-11ea-8838-541420ca16f7.png)

@SuperKogito can you take a look soon?

**Comment by SuperKogito** [comment]
This is interesting because the filter condition should filter these links out.
https://github.com/urlstechie/urlchecker-python/blob/af9d7acf9f40359e98f3b80f3856b334ecc1b0a9/urlchecker/core/fileproc.py#L130

but it seems that the pattern matches `{*}` and not just `*}` :disappointed:
