### ISSUE TITLE
Syntax for 'file_types' including dotfiles

### ISSUE THREAD

**Issue by rootwork** [urlstechie/urlchecker-python#46]
Let's say I wanted to check all `.html` files, but also ALL dotfiles -- that is, files that have no filename, only an extension (`.editorconfig`, say, or `.pylintrc`).

Why would I want to do that? Because sometimes I use comments in these files to source where I got something, and I want to check URLs there to know if/when they break.

I'm sure this is an edge case, but is there a syntax for `file_types` that would include all dotfiles (not just specific ones)? I tried a few different things but none of them worked.

Thanks!

**Comment by vsoch** [comment]
okay - I should be able to put in a PR to fix this, or describe a way to do it sometimes tomorrow. Stay tuned!

**Comment by rootwork** [comment]
Awesome, thanks!

I meant to say in the original report that if you leave `file_types` blank, it seems to omit any dotfiles (but it includes all other files).

**Comment by vsoch** [comment]
Yes that's correct, it defaults to python and markdown.

**Comment by vsoch** [comment]
@rootwork here is a PR for you to test! I put examples in the description to show how to match a particular extension, or general pattern (like dotfiles). https://github.com/urlstechie/urlchecker-python/pull/47

**Comment by vsoch** [comment]
Closed with #47.

**Comment by vsoch** [comment]
@rootwork note that I won't do a new release until I've done the second PR to update the client arguments, likely this weekend.

**Comment by rootwork** [comment]
@vsoch Thanks so much for your work on this!
