### ISSUE TITLE
Minor: misspelling 'whitetlist'

### ISSUE THREAD

**Issue by rootwork** [urlstechie/urlchecker-python#48]
This is a followup to [urlchecker-action #72](https://github.com/urlstechie/urlchecker-action/issues/72): The misspelling "whitetlist" (note extra T) is in the python script.

`check.py` line 66
`README.md` lines 115, 192

I was going to create a PR, but then I thought you might be considering changing "white(_)list(ed)" options to "exclude(d)" to match the change in urlchecker-action, in which case much more than these lines would be getting changed.

As I noted in the title, this is a minor fix, just wanted to follow up since I mentioned it in the original issue and figured out where it was from.

**Comment by vsoch** [comment]
Yes we'd definitely change them! I was actually considering doing this for a recent PR: https://github.com/urlstechie/urlchecker-python/pull/47. The testing on travis didn't trigger, and I needed my colleague @SuperKogito to take a look (or anyone to review it) but nobody has yet. If we can get that finalized and merged I will gladly do a second PR to change the terms and fix the spelling errors.

**Comment by vsoch** [comment]
Sounds good! Thank you @SuperKogito !

@rootwork I'll jump on the issue here after that. We can have a new release for the GitHub action with this added ability to specify filetypes, along with the updated command and fixed spelling errors.

**Comment by rootwork** [comment]
Cool cool. Thank you!
