### ISSUE TITLE
add a pre-commit hook

### ISSUE THREAD

**Issue by aerickson** [urlstechie/urlchecker-python#54]
urlchecker is sweet. It would be great if it was easier to run. Lots of projects use pre-commit (https://pre-commit.com/).

I think all that's required is to create a file like Black provides:

https://github.com/psf/black/blob/master/.pre-commit-hooks.yaml

**Comment by vsoch** [comment]
That’s a cool idea! What are the advantages to having some custom yaml (like black) vs. just adding the urlchecker command to a pre commit hook file?

**Comment by aerickson** [comment]
I don't think pre-commit supports adding bare commands to the config. It wants to know how to run the tool, etc.

**Comment by vsoch** [comment]
hey @aerickson ! So I finally took a closer look, and decided to give it a shot to generate a pre-commit hook! Design wise, I think this likely is better to live in a different repository, the reason being that we need to change the client (as you found) and we can easily do that in a custom module. @aerickson and @SuperKogito would you care to try it out?

**Comment by SuperKogito** [comment]
Great work @vsoch.
This looks nice, I am curious to see how it goes further. 
Unfortunately I will be able to check this at the earliest on Sunday.

**Comment by vsoch** [comment]
Closing, please re-open an issue on the pre-commit repo if there are any!
