### ISSUE TITLE
Provide base container with urlchecker-python

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-python#6]
heyo! So this will take a bit more time to develop, but I'm working on the action refactor and I think we can really streamline it if we release a build for the container here. For a quick solution I'm going to build the container and manually push to Docker Hub to use as a base, but I wanted to open this issue so we can discuss:

 - an organization for containers built here
 - an automated build on release to do it.

**Comment by vsoch** [comment]
Hmm, another thought - we _could_ try the GitHub docker registry - I've never done it. Let me look into this quickly.

**Comment by SuperKogito** [comment]
I am not sure what will the GitHub docker registry add tbh but on first look it does seem simple to use.
What do you mean by automated build on release? Build for the test repo?

**Comment by vsoch** [comment]
So when we push to master (or release) a container is built and tagged with the correct version. Another option that would work nicely is quay.io - I could use your email for an "urlstechie" org, would that work?

**Comment by vsoch** [comment]
okay I'm going to do a total experiment with package registry first - never done this before so here goes nothing!

**Comment by vsoch** [comment]
To give you a little more context - when we run a GitHub action, the Dockerfile provided is built. In the case of a small install on top of a base, it's fairly speedy. But in the case that we want to provide more substantial bases (and not need to build) we should provide via  a registry. I'm rethinking this now - since this is something that will take careful work to choose a registry, set up the CI, I don't want to do it rushed.

**Comment by SuperKogito** [comment]
> So when we push to master (or release) a container is built and tagged with the correct version. Another option that would work nicely is quay.io - I could use your email for an "urlstechie" org, would that work?

hmm urlstechie has its own gmail, urlstechie@gmail.com, if you need access to it, email me at superkogito@gmail.com and I will give you the credentials.

**Comment by vsoch** [comment]
okay let's hold off on this for now - I'm going to do a simpler container base so it's faster, opening PR for the action now.

**Comment by vsoch** [comment]
I've used quay.io before (and trust it much more than the other two) so I just made an organization on there with the email. The only thing I need your help with is:

1. setting a gravatar to be the urlstechie logo (see how it pulls from there)

![image](https://user-images.githubusercontent.com/814322/77236806-88512e00-6b87-11ea-810e-e3d29cb1db6d.png)

2. Creating an account on quay.io, telling me the username, so I can add you to the organization.

Quay is >> the other two because it gives repository and permission specific tokens.

**Comment by SuperKogito** [comment]
I just set up the gravatar for urlstechie so the logo should be updated. 
My quay.io is the following https://quay.io/user/superkogito

**Comment by vsoch** [comment]
okay looks good! I set up the empty repository, so now I just need to write the recipe for it.

**Comment by vsoch** [comment]
We finished this, wow! I wrote up and shared a small post, and I think the code bases are in relatively good shape if we want to start sharing more widely (reddit, hacker news, etc) https://twitter.com/vsoch/status/1241838940622958592?s=21

**Comment by SuperKogito** [comment]
Great work Vanessa! The article you wrote is a great way to promote the urlstechie tools and the Twitter post should also help get us more attraction :clap: 
please refer to  https://github.com/urlstechie/urlchecker-python/issues/13 for more on this topic.

**Comment by vsoch** [comment]
Gotcha! I read over #13 and I do have some thoughts / ideas, but I want to sleep on it.
