### ISSUE TITLE
`http` filter in for loop

### ISSUE THREAD

**Issue by SuperKogito** [urlstechie/urlchecker-python#65]
@vsoch I came across this while reviewing the latest PR. 
https://github.com/urlstechie/urlchecker-python/blob/1f9bd5c88cef73af38700531bffdfb581d4c441e/urlchecker/core/urlproc.py#L182

How important is the filter using `http`? shouldn't the REGEX deliver that already?

**Comment by vsoch** [comment]
I do think we need it - our regex https://github.com/urlstechie/urlchecker-python/blob/1f9bd5c88cef73af38700531bffdfb581d4c441e/urlchecker/core/urlmarker.py  is pretty forgiving about matching other kinds of webby content. but we primarily are interested in https/http

```python
In [3]: re.search(FINAL_REGEX, "https://google.com")                                                                                         
Out[3]: <re.Match object; span=(0, 18), match='https://google.com'>

In [4]: re.search(FINAL_REGEX, "http://google.com")                                                                                          
Out[4]: <re.Match object; span=(0, 17), match='http://google.com'>

In [5]: re.search(FINAL_REGEX, "ftp://google.com")                                                                                           
Out[5]: <re.Match object; span=(6, 16), match='google.com'>

In [6]: re.search(FINAL_REGEX, "git@github.com:google/google.com")                                                                           
Out[6]: <re.Match object; span=(22, 32), match='google.com'>
```
