### ISSUE TITLE
adding type hints in code (PEP 484)

### ISSUE THREAD

**Issue by SuperKogito** [urlstechie/urlchecker-python#66]
@vsoch How do you feel about adding [type hints](https://peps.python.org/pep-0484/) to our code? 
This seems to be the trend these days and it will provide us with some type security and it doesn't seem to be that much of a hassle.

**Comment by vsoch** [comment]
I would be down with it!

**Comment by SuperKogito** [comment]
okay I will try to do this next Weekend :)
