### ISSUE TITLE
failing url check.

### ISSUE THREAD

**Issue by shahzebsiddiqui** [urlstechie/urlchecker-python#71]
According to https://github.com/buildtesters/buildtest/runs/6903580431?check_suite_focus=true i am getting failure on this url https://www.hpcwire.com/2019/01/17/pfizer-hpc-engineer-aims-to-automate-software-stack-testing/

It would be nice if there was extra output to explain why these url are breaking. I know this urlchecker does work on most part and i can ignore this from list.

![Screen Shot 2022-06-15 at 12 11 00 PM](https://user-images.githubusercontent.com/12942230/173875003-047dfa71-0fa0-424c-8053-a8ed7ff09987.png)

I don't want to use `force_pass : true` though i do want the action to pass.

I have not tried `verbose: true` but does this provide the detail for debugging.

**Comment by vsoch** [comment]
okay will have a PR for you to test this evening (did it last night and forgot to open it, lol).

**Comment by shahzebsiddiqui** [comment]
For now I excluded the url from CI check I can add it back in or I can test it out in the next release

**Comment by vsoch** [comment]
@shahzebsiddiqui good news! I have tested a new user agent library that (I think) will do better for this particular set of URLs - you can test the `fix/ansi-colors` branch for the action (just pushed a new build for it).

Note that this doesn't fix every url issue we've seen - I'm thinking I'm going to need to use selenium for this small set of URLs, but if this user agent fix handles just a few of the issues I'd like to get it out sooner than later!
