### ISSUE TITLE
Urlchecker doesn't clean previous configuration. Got `file types: ['.md', '.py']` without adding such pattern

### ISSUE THREAD

**Issue by sturivny** [urlstechie/urlchecker-python#81]
**Preconditions:**
* Python 3.9.13
* urlchecker version: 0.0.31

**Steps to reproduce:**
1. Clone the repo: https://gitlab.com/cki-project/documentation
1. Navigate to the repo: `cd documentation`
1. Execute: urlchecker check . `--timeout 60 --retry-count 5 --files "content/docs/hacking/contributing/documentation/index.md"`

Actual result:
```
❯ urlchecker check .      --timeout 60     --retry-count 5  --files "content/docs/hacking/contributing/documentation/index.md"
           original path: .
              final path: /home/sturivny/git-cki/documentation
               subfolder: None
                  branch: main
                 cleanup: False
              file types: ['.md', '.py']
                   files: ['content/docs/hacking/contributing/documentation/index.md']
               print all: True
                 verbose: False
           urls excluded: []
   url patterns excluded: []
  file patterns excluded: []
              force pass: False
             retry count: 5
                    save: None
                 timeout: 60

```

**Expected result:**
No Errors

**Comment by SuperKogito** [comment]
can you please explain what do you mean with "clean previous configuration" or include the error in the the issue? I am not sure I follow.

**Comment by sturivny** [comment]
I've played with the urlchecker and run the command with `--file-types "*.md,*.py"` key
Then I run:
```
urlchecker check . --timeout 60 --retry-count 5 --files "content/docs/hacking/contributing/documentation/index.md"
```
without the `--file-types` key and got: `file types: ['.md', '.py'] ` in the output

**Comment by SuperKogito** [comment]
That's not a bug. Just a coincidence I guess. As you can see here: 
https://github.com/urlstechie/urlchecker-python/blob/dad0bdc9f887508889086138fd6fa228e1c6da05/urlchecker/core/check.py#L62

The default value of `file types` is `['.md', '.py']`, that's why you keep seeing that when you don't specify a value for it. If you want to include a different type or all types you will have to change the value `file types`. Please check out the [README](https://github.com/urlstechie/urlchecker-python/blob/master/README.md) for more examples on that.

**Comment by vsoch** [comment]
And @sturivny for some of these, I think we are seeing "no errors" but actually the last message is that there is an error with the workers, so there is a bug somewhere!

**Comment by sturivny** [comment]
@vsoch Yep, you are right, and looks like it has a fix: https://github.com/urlstechie/urlchecker-python/pull/82
