### ISSUE TITLE
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI

### ISSUE THREAD

**Issue by danschef** [urlstechie/urlchecker-python#84]
So far, `pip install urlchecker` was everything needed to install the package. With version 0.0.33,  this fails with:

```bash
(env) ~$ pip install urlchecker
Collecting urlchecker
  Downloading urlchecker-0.0.33.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
urlchecker depends on fake-useragent@ git+https://github.com/danger89/fake-useragent@master#egg=fake-useragent
```

If I follow the installation instructions in your README file,  I get this:

```bash
(urlchecker) ~$ pip install git+https://github.com/danger89/fake-useragent.git
Collecting git+https://github.com/danger89/fake-useragent.git
  Cloning https://github.com/danger89/fake-useragent.git to /tmp/pip-req-build-qvfvjz9m
  Running command git clone --filter=blob:none --quiet https://github.com/danger89/fake-useragent.git /tmp/pip-req-build-qvfvjz9m
  Resolved https://github.com/danger89/fake-useragent.git to commit a8f2b57910cdb496dcebd4a828f6e33984b2124f
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: fake-useragent
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.12-py3-none-any.whl size=13815 sha256=b897ee62f3d8cd7f726d523aa4e2b5d99a18fdaba36804312bd778f797651233
  Stored in directory: /tmp/pip-ephem-wheel-cache-asneomg1/wheels/4a/80/0e/42b3e4541f3f2e603f91cf7c5c83b5342621e45a46d45b98ed
Successfully built fake-useragent
Installing collected packages: fake-useragent
Successfully installed fake-useragent-0.1.12

(urlchecker) ~$ pip install urlchecker
Collecting urlchecker
  Using cached urlchecker-0.0.33.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
urlchecker depends on fake-useragent@ git+https://github.com/danger89/fake-useragent@master#egg=fake-useragent
```

**Comment by vsoch** [comment]
Try installing the previous version for now - we will have to figure this dependency out.

**Comment by vsoch** [comment]
@danschef the creator of the library has filed an issue with pypi - it's a complicated situation because we need the new library - the previous developer (that has the pypi package) hasn't updated it since 2020 (and I hope he/she is OK). For now it's a bug, and hopefully if/when the package gets on pypi for a future version this will be fixed!

**Comment by danschef** [comment]
So far as I can see, there are two new releases of fake-useragent on PyPI: https://pypi.org/project/fake-useragent/#history

However, the installation of urlchecker 0.0.33 still fails with the same error. I think replacing https://github.com/urlstechie/urlchecker-python/blob/73536c575ba1ed725edba55b43d6305d899787ca/setup.py#L91 with `fake-useragent` should fix it. This directly gets the package from PyPI.

**Comment by vsoch** [comment]
Thanks for the ping! This should be fixed, and the action will be updated soon too. If you are using a webdriver (it's a fallback for hard cases) at least for chrome I needed to update to 107.x

**Comment by danschef** [comment]
Thanks, works fine.

**Comment by danschef** [comment]
@romulogoncalves
